//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelierMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompteAdmin
    {
        public int Id { get; set; }
        public string Motif { get; set; }
        public string NomBoite { get; set; }
        public string NomDemandeur { get; set; }
        public string StatutDemande { get; set; }
        public string Info { get; set; }
        public int ServiceId { get; set; }
        public string EmailAdmin { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
