//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelierMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandeCreation
    {
        public int Id { get; set; }
        public System.DateTime DateDemande { get; set; }
        public string Numero { get; set; }
        public string TitreDeDemande { get; set; }
    
        public virtual RespService RespService { get; set; }
        public virtual Service Service { get; set; }
    }
}
