//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelierMVVM.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmailDBEntitiesContainer : DbContext
    {
        public EmailDBEntitiesContainer()
            : base("name=EmailDBEntitiesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Personnel> Personnels { get; set; }
        public virtual DbSet<CompteAdmin> CompteAdmins { get; set; }
        public virtual DbSet<AdresseDomicile> AdresseDomiciles { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<DemandeCreation2> DemandeCreation2 { get; set; }
    }
}
