//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelierMVVM.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVVMGestionEmailDBEntities : DbContext
    {
        public MVVMGestionEmailDBEntities()
            : base("name=MVVMGestionEmailDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdresseDomicile> AdresseDomiciles { get; set; }
        public virtual DbSet<CompteAdmin> CompteAdmins { get; set; }
        public virtual DbSet<Compte> Comptes { get; set; }
        public virtual DbSet<DemandeCreation2> DemandeCreation2 { get; set; }
        public virtual DbSet<Personnel> Personnels { get; set; }
        public virtual DbSet<Personnels_RespService> Personnels_RespService { get; set; }
        public virtual DbSet<Service> Services { get; set; }
    }
}
