//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelierMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Matricule { get; set; }
        public string TypeDeContrat { get; set; }
        public System.DateTime DateNaissance { get; set; }
        public string LieuNaissance { get; set; }
        public string Photo { get; set; }
        public string Profil { get; set; }
        public string EmailPersonnel { get; set; }
        public int AdresseDomicile_Id { get; set; }
        public int Service1_Id { get; set; }
    
        public virtual AdresseDomicile AdresseDomicile { get; set; }
        public virtual Service Service { get; set; }
        public virtual Personnels_RespService Personnels_RespService { get; set; }
    }
}
