//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelierMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnels_RespService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personnels_RespService()
        {
            this.DemandeCreation2 = new HashSet<DemandeCreation2>();
        }
    
        public int RespServiceId { get; set; }
        public int DemandeCreationId { get; set; }
        public int Id { get; set; }
        public int Service_Id { get; set; }
    
        public virtual Personnel Personnel { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandeCreation2> DemandeCreation2 { get; set; }
    }
}
