//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelierMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespService : Personnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RespService()
        {
            this.DemandeCreation2 = new HashSet<DemandeCreation2>();
        }
    
        public int RespServiceId { get; set; }
        public int DemandeCreationId { get; set; }
    
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandeCreation2> DemandeCreation2 { get; set; }
    }
}
